//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by microsip.rc
//
#define ID_STATUSBAR                    101
#define IDD_MICROSIP_DIALOG             102
#define IDC_SINGLE_MODE                 102
#define IDC_SYSLINK_SINGLE_MODE         103
#define IDC_PREVIEW                     104
#define ID_PREVIEW                      105
#define IDC_LOCAL_DTMF                  106
#define IDC_SYSLINK_LOCAL_DTMF          107
#define IDC_BITRATE_264                 108
#define IDC_BITRATE_263                 109
#define IDC_EDIT_AUTHID                 110
#define IDC_SYSLINK_AUTHID              111
#define IDC_ENABLE_LOG                  112
#define IDC_SYSLINK_DISPLAY_PASSWORD    113
#define IDR_MAINFRAME                   128
#define IDD_RINGIN                      131
#define IDD_ACCOUNT                     132
#define IDR_WAVE_RINGIN                 136
#define IDR_WAVE_RINGOUT                137
#define IDI_OFFLINE                     146
#define IDI_ONLINE                      147
#define IDI_UNKNOWN                     148
#define IDR_MENU_CONTACT                153
#define IDD_ADD                         155
#define IDD_SETTINGS                    156
#define IDD_MESSAGES                    158
#define IDR_MENU_TRAY                   161
#define IDD_DIALER                      163
#define IDD_CONTACTS                    164
#define IDR_WAVE_RINGIN2                168
#define IDI_AWAY                        172
#define IDD_ACCOUNT_CUSTOM              175
#define IDI_LOGO                        175
#define IDI_CLOSE_2                     176
#define IDD_TRANSFER                    177
#define IDI_CLOSE                       178
#define IDC_DELETE                      1009
#define IDC_CALLER_NAME                 1012
#define IDC_EDIT_USERNAME               1013
#define IDC_EDIT_PASSWORD               1014
#define IDC_CALLER_ADDR                 1014
#define IDC_EDIT_SERVER                 1015
#define IDC_CALLED                      1015
#define IDC_EDIT_DISPLAYNAME            1016
#define IDC_EDIT_DOMAIN                 1017
#define IDC_EDIT_PROXY                  1018
#define IDC_STUN                        1019
#define IDC_CALL_INFO                   1020
#define IDC_CONTACTS                    1025
#define IDC_EDIT_NUMBER                 1028
#define IDC_EDIT_NAME                   1029
#define IDC_AUTO_ANSWER                 1031
#define IDC_DISABLE_VAD                 1032
#define IDC_BROWSE                      1033
#define IDC_DEFAULT                     1034
#define IDC_RINGING_SOUND               1035
#define IDC_DISABLE_H264                1038
#define IDC_DISABLE_H263                1040
#define IDC_LIST                        1048
#define IDC_MESSAGE                     1049
#define IDC_KEY_1                       1050
#define IDC_TAB                         1051
#define IDC_KEY_3                       1052
#define IDC_KEY_4                       1053
#define IDC_KEY_5                       1054
#define IDC_KEY_6                       1055
#define IDC_KEY_7                       1056
#define IDC_KEY_8                       1057
#define IDC_KEY_9                       1058
#define IDC_KEY_STAR                    1059
#define IDC_KEY_0                       1060
#define IDC_KEY_GRATE                   1061
#define ID_TAB                          1065
#define IDC_NUMBER                      1066
#define IDC_KEY_2                       1067
#define IDC_CLEAR                       1069
#define IDC_KEY_PLUS                    1070
#define IDC_DISABLE_LOCAL               1071
#define IDC_TRANSPORT                   1072
#define IDC_PUBLIC_ADDR                 1073
#define IDC_SRTP                        1074
#define IDC_ICE                         1075
#define IDC_PRESENCE                    1076
#define IDC_LISTEN_PORT                 1076
#define IDC_CALL                        1078
#define IDC_CALL_END                    1080
#define IDC_VIDEO_CALL                  1081
#define IDC_PUBLISH                     1082
#define IDC_VID_CAP_DEV                 1085
#define IDC_MICROPHONE                  1086
#define IDC_SPEAKERS                    1087
#define IDC_VIDEO                       1089
#define IDC_VIDEO_CODEC                 1089
#define IDC_UPDATES_INTERVAL            1103
#define IDC_SYSLINK_RINGING_SOUND       1104
#define IDC_SYSLINK_AUTO_ANSWER         1105
#define IDC_SYSLINK_DISABLE_LOCAL       1106
#define IDC_SYSLINK_DISABLE_VAD         1107
#define IDC_SYSLINK_SIP_SERVER          1108
#define IDC_SYSLINK_DISABLE_H264        1108
#define IDC_SYSLINK_SIP_PROXY           1109
#define IDC_SYSLINK_DISABLE_H263        1109
#define IDC_SYSLINK_USERNAME            1110
#define IDC_SYSLINK_DISABLE_VAD2        1110
#define IDC_SYSLINK_AUDIO_CODECS        1110
#define IDC_SYSLINK_DOMAIN              1111
#define IDC_SYSLINK_PASSWORD            1112
#define IDC_SYSLINK_NAME                1113
#define IDC_SYSLINK_ENCRYPTION          1114
#define IDC_SYSLINK_TRANSPORT           1115
#define IDC_SYSLINK_PUBLIC_ADDRESS      1116
#define IDC_SYSLINK_LOCAL_PORT          1117
#define IDC_SYSLINK_PUBLISH_PRESENCE    1118
#define IDC_AUDIO_CODECS_ALL            1118
#define IDC_SYSLINK_STUN_SERVER         1119
#define IDC_AUDIO_CODECS                1119
#define IDC_SYSLINK_ICE                 1120
#define IDC_SYSLINK_PREFIX              1121
#define IDC_SPIN_MODIFY                 1125
#define IDC_SPIN_ORDER                  1127
#define IDC_HOLD                        1128
#define IDC_TRANSFER                    1129
#define IDC_END                         1132
#define IDC_RICHEDIT21                  1133
#define ID_ADD                          32774
#define ID_DELETE                       32775
#define ID_EDIT                         32779
#define ID_EXIT                         32785
#define ID_ACCOUNT                      32786
#define ID_SETTINGS                     32787
#define ID_WEBSITE                      32788
#define ID_CALL                         32795
#define ID_CHAT                         32796
#define ID_LOG                          32800

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        181
#define _APS_NEXT_COMMAND_VALUE         32801
#define _APS_NEXT_CONTROL_VALUE         1135
#define _APS_NEXT_SYMED_VALUE           114
#endif
#endif
